title: PhosNetVis | Docs
logo: "/assets/images/docsnetvis.png"
description: Documentation page for the PhosNetVis!
theme: just-the-docs

url: https://docs.phosnetvis.app

aux_links:
  Back to PhosNetVis: https://phosnetvis.app
