title: PhosNetVis | Docs
logo: "/assets/images/docsnetvis.png"
description: Documentation page for the PhosNetVis!
theme: just-the-docs
color_scheme: phos

url: https://gumuslab.github.io/phosnetvis-docs/

aux_links:
  Back to PhosNetVis: https://gumuslab.github.io/PhosNetVis
